### ISSUE TITLE
Labyrinth import fails

### ISSUE THREAD

**Issue by ricklefsv** [olab/Open-Labyrinth#89]
Labyrinth import fails with the error:
```
Error, labyrinth was not imported correctly. Missing argument 3 for Model_Leap_Map_Node_Section::createSection(), called in .../www/application/classes/importexport/mvpvpsimformatsystem.php on line 697 and defined 
```
I looked up this piece of code. It has:
```php
$nodeSectionId = DB_ORM::model('map_node_section')->createSection($map->id, $nodeSectionData);
```
createSection has two arguments, but when you look at its definition in www/application/classes/model/leap/map/node/section.php (line 90) it has three arguments. The missing one is `$orderBy`:
```php
public function createSection($mapId, $values, $orderBy) {
```
I tried to modify line 697 to 
```php
$nodeSectionId = DB_ORM::model('map_node_section')->createSection($map->id, $nodeSectionData,false);
```
It then imports the labyrinth but then gives the error that the property is not valid. Apparently putting `false` does not work. What should I do? What argument should I pass? I need to import this labyrinth as quick as possible, and thought it is just a trivial thing. But apparently not so :(

**Comment by d-semenyuk** [comment]
@ricklefsv Issue has been fixed and committed to "release-candidate" branch. Will be included in next release.
Thank you for reporting.

Please let me know if you have any questions.

**Comment by Mike19841984** [comment]
PHP 5.5.27, OLab 3.3.1, problem still there, would very much appreciate a fix.

**Comment by ricklefsv** [comment]
The solution is simple. But it requires editing the source files.

In the file www/application/classes/model/leap/map/node/section.php (line 90)  there is a statement:
```php
 public function createSection($mapId, $values, $orderBy) {
```
It should be replaced by:
```php
public function createSection($mapId, $values, $orderBy = 'random') {
```

**Comment by Mike19841984** [comment]
That's what's already there.

In the settings tab I get:

Error, labyrinth was not imported correctly. preg_replace(): The /e modifier is deprecated, use preg_replace_callback instead

When trying to import a labyrinth the following is displayed:

Whoops! Looks like something got lost in the Labyrinth.
A message has been sent to the technical team. They will look into this issue.
Please use the "back" arrow on your web browser to return to where you were before this happened.

**Comment by sergey-rud** [comment]
Fixed.
